name: Release

on:
  push:
    # This branch pattern needs to be allowed in the environment
    # protection rules.
    tags:
      - v*

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: |
          apt update
          apt install -y zip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build collections bundle
        run: ./tools/bundle.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: collections.zip
